# Generated by Django 4.2.7 on 2023-11-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_agenda_datanascimento_alter_agenda_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='DataNascimento',
            field=models.DateField(verbose_name='Data de Nascença'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
