# Generated by Django 4.2.6 on 2023-11-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0008_alter_telefone_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('RES', 'Residencial'), ('COM', 'Comercial'), ('REC', 'Recado'), ('CEL', 'Celular')], max_length=3),
        ),
    ]
